volumes:
  shorturl_fileshare_data:
    name: shorturl_fileshare_data

services:
  backend_java:
    image: somik123/shorturl-fileshare
    container_name: shorturl_fileshare_java
    restart: unless-stopped
    volumes:
      - shorturl_fileshare_data:/usr/app/data
    environment:
      SHORTURL_USER: admin
      SHORTURL_PASS: zR6CzF9bZp3@HTPzaaY%2Fzv
      SHORTURL_PASS_HIDE: no
      SHORTURL_LENGTH: 5
      FILEURL_LENGTH: 16
      SHORTURL_DB_HOST: db
      SHORTURL_DB_NAME: XYgPZX7WCiW
      SHORTURL_DB_USER: mhvXD4AuBi7
      SHORTURL_DB_PASS: DYg3FejmiQ4RdNcFHYNU3NWs
      UPLOADFILE_MAX_SIZE: 50
      TELEGRAM_APIKEY: 1234567890:ABcd7EFghIJk3lMN_ABc5dEF6ghIJklMNop
      TELEGRAM_AUTHKEY: SADBniacAVEY9PQvaV7mhnMG
      TELEGRAM_ADMINID: 123456789
      SITE_FULL_URL: https://www.example.com/
      IP2C_URL: https://ip2country.example.com/?ip=
      ALLOWED_COUNTRIES: all
      TZ: Asia/Singapore
    ports:
      - 6080:8080
