volumes:
  shorturl_fileshare_data:
    name: shorturl_fileshare_data
  ip2country_db:
      name: ip2country_db

services:
  backend_java:
    image: somik123/shorturl-fileshare
    container_name: shorturl_fileshare_java
    restart: unless-stopped
    volumes:
      - shorturl_fileshare_data:/usr/app/data
    environment:
      SHORTURL_USER: admin
      SHORTURL_PASS: zR6CzF9bZp3@HTPzaaY%2Fzv
      SHORTURL_PASS_HIDE: no
      SHORTURL_LENGTH: 5
      FILEURL_LENGTH: 16
      PAGINATION_SIZE: 25
      SHORTURL_DB_HOST: db
      SHORTURL_DB_NAME: XYgPZX7WCiW
      SHORTURL_DB_USER: mhvXD4AuBi7
      SHORTURL_DB_PASS: DYg3FejmiQ4RdNcFHYNU3NWs
      UPLOADFILE_MAX_SIZE: 50
      TELEGRAM_APIKEY: 1234567890:ABcd7EFghIJk3lMN_ABc5dEF6ghIJklMNop
      TELEGRAM_AUTHKEY: SADBniacAVEY9PQvaV7mhnMG
      TELEGRAM_ADMINID: 123456789
      SITE_FULL_URL: https://www.example.com/
      IP2C_URL: http://ip2c/api/v2/
      ALLOWED_COUNTRIES: US,CA,SG,MY,AU
      TZ: Asia/Singapore
    ports:
      - 6080:8080

  ip2c:
    container_name: ip2country
    image: somik123/ip2country
    restart: unless-stopped
    volumes:
      - ip2country_db:/var/www/html/db/
    # Uncomment the next 2 lines to enable port mapping for ip2country
    # ports:
    #   - 6088:80